# Directories arguments for Training only
data_root: "datasets/HEVI"
ego_data_root: "datasets/HEVI/ego_motion"
checkpoint_dir: "checkpoints/fol_ego_checkpoints"

# Directories arguments for running on Anomaly Detection videos only
# best_fol_model: 'checkpoints/fol_ego_checkpoints/fol_ego_0.5sec/fol_epoch_078_loss_0.0013.pt'
# best_ego_pred_model: "/home/brianyao/Documents/stad2019iros-pytorch/checkpoints/ego_pred_checkpoints/epoch_080_loss_0.001.pt"
best_fol_model: 'checkpoints/fol_ego_checkpoints_rnn/fol_epoch_054_loss_0.0127.pt'
best_ego_pred_model: 'checkpoints/ego_pred_checkpoints_rnn/epoch_099_loss_0.0012.pt'

test_dataset: "DoTA" 
label_file: 'datasets/DoTA/annotations'

track_dir: "datasets/DoTA/frames/det"
flow_dir: "datasets/DoTA/flownet2"
ego_motion_dir: "datasets/DoTA/ego_motion"
img_dir: "datasets/DoTA/frames"
save_dir: "datasets/DoTA/fvl_ego_results_rnn"

# dataset arguments
seed_max: 5
segment_len: 16

# training parameters
nb_fol_epoch: 100
nb_ego_pred_epoch: 200
lr: 0.0001

lambda_fol: 1
lambda_ego: 1
device: 'cuda'
# fol model parameters
pred_timesteps: 5
input_embed_size: 512
flow_enc_size: 512
box_enc_size: 512
with_ego: True

enc_hidden_size: 512 # no use
enc_concat_type: "average"
predictor_input_size: 512
dec_hidden_size: 512
pred_dim: 4


# ego_pred model parameters
ego_embed_size: 128
ego_enc_size: 128
ego_dec_size: 128
ego_pred_input_size: 128
ego_dim: 3

# dataloader parameters
batch_size: 32
shuffle: True
num_workers: 0

# image parameters
H: 720
W: 1280
channels: 3

flow_roi_size: [5,5,2]

# Anomaly detection parameters
max_age: 10
